# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

default_language_version = { python = "python3.12" }

[[repos]]
repo = "https://github.com/astral-sh/uv-pre-commit"
rev = "0.12.3"
hooks = [
  { id = "uv-lock" }
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.12"
hooks = [
  { id = "ruff-format" },
  { id = "ruff-check" }
]

[[repos]]
repo = "https://github.com/rhysd/actionlint"
rev = "v1.7.12"
hooks = [
  { id = "actionlint" }
]

[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
  {
    id = "check-added-large-files",
    args = ["--maxkb=1000"]
  },
  { id = "check-case-conflict" },
  { id = "end-of-file-fixer" },
  { id = "mixed-line-ending" },
  {
    id = "pretty-format-json",
    args = [
      "--no-sort-keys",
      "--autofix",
      "--indent",
      "2"
    ]
  },
  { id = "trailing-whitespace" }
]

[[repos]]
repo = "https://github.com/jumanjihouse/pre-commit-hook-yamlfmt"
rev = "0.2.3"
hooks = [
  {
    id = "yamlfmt",
    args = [
      "--mapping",
      "2",
      "--sequence",
      "4",
      "--offset",
      "2",
      "--width",
      "4096"
    ]
  }
]

[[repos]]
repo = "https://github.com/adrienverge/yamllint.git"
rev = "v1.38.0"
hooks = [
  {
    id = "yamllint",
    args = [
      "--format",
      "parsable",
      "--strict"
    ]
  }
]

[[repos]]
repo = "https://github.com/DetachHead/basedpyright-prek-mirror"
rev = "1.39.9"
hooks = [
  {
    id = "basedpyright",
    files = "^(very_slow_movie_player/|pyproject\\.toml$)",
    pass_filenames = false,
    additional_dependencies = [
      "pydantic==2.9.2",
      "wg-utilities==5.15.4",
      "youtube-dl-nightly==2024.8.7",
      "Pillow==10.4.0",
      "httpx==0.27.2",
      "types-RPi.GPIO",
      "ffmpeg-python==0.2.0"
    ]
  }
]

[[repos]]
repo = "https://github.com/pre-commit/pygrep-hooks"
rev = "v1.10.0"
hooks = [
  { id = "python-check-blanket-noqa" },
  { id = "python-check-blanket-type-ignore" },
  { id = "python-check-mock-methods" }
]

[[repos]]
repo = "https://github.com/codespell-project/codespell"
rev = "v2.4.3"
hooks = [
  {
    id = "codespell",
    additional_dependencies = ["tomli==2.0.1"]
  }
]

[[repos]]
repo = "https://github.com/jendrikseipp/vulture"
rev = "v2.12"
hooks = [
  { id = "vulture" }
]

[[repos]]
repo = "https://github.com/fredrikaverpil/creosote"
rev = "v3.0.2"
hooks = [
  { id = "creosote" }
]
