---
name: Manage Repo Labels

on:
  push:
    branches:
      - main
    paths:
      - .github/repo_labels.yml
  workflow_dispatch:

jobs:
  manage-repo-labels:
    name: Manage Repo Labels
    # yamllint disable-line rule:line-length
    uses: worganisation/github-config-files/.github/workflows/__manage-repo-labels.yml@61df7cff685739aef6427c565445b5508619cd0a # 0.10.0
    permissions:
      contents: read
      issues: write
